In [1]:
import numpy as np

In [4]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [5]:
list(range(0,6))

[0, 1, 2, 3, 4, 5]

In [6]:
list(range(0.4,1.8))

TypeError: 'float' object cannot be interpreted as an integer

In [12]:
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [13]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [14]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [19]:
np.logspace(1,5, 20, base=2)

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])

In [26]:
arr = np.ones((3,4))

In [27]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [36]:
arr*8

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [37]:
np.empty((3,4))

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [39]:
arr1 = np.eye(5)

In [40]:
 arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
import pandas as pd

In [42]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [43]:
np.random.rand(3,4)

array([[0.21967346, 0.52945197, 0.52387288, 0.77159733],
       [0.26954274, 0.18349003, 0.10268196, 0.93924608],
       [0.8060071 , 0.47496203, 0.89260043, 0.68686603]])

In [53]:
np.random.randn(3,3)

array([[ 0.71447857,  1.64061874, -0.24395851],
       [-0.51280817, -2.64000987,  1.85559521],
       [-0.59984728,  0.15787687,  0.56657068]])

In [55]:
arr2 = np.random.randint(1,5, (3,4))

In [56]:
arr2

array([[1, 2, 3, 1],
       [1, 1, 4, 4],
       [2, 1, 4, 2]])

In [57]:
arr2.size

12

In [58]:
arr2.shape

(3, 4)

In [59]:
arr2.reshape(2,6)

array([[1, 2, 3, 1, 1, 1],
       [4, 4, 2, 1, 4, 2]])

In [60]:
arr2.reshape(4,3)

array([[1, 2, 3],
       [1, 1, 1],
       [4, 4, 2],
       [1, 4, 2]])

In [61]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [62]:
arr2.reshape(6,2)

array([[1, 2],
       [3, 1],
       [1, 1],
       [4, 4],
       [2, 1],
       [4, 2]])

In [63]:
arr2.reshape(2,2,3)

array([[[1, 2, 3],
        [1, 1, 1]],

       [[4, 4, 2],
        [1, 4, 2]]])

In [66]:
arr2.reshape(4,-11)

array([[1, 2, 3],
       [1, 1, 1],
       [4, 4, 2],
       [1, 4, 2]])

In [67]:
arr3 = np.random.randint(1,10, (5,6))

In [68]:
arr3

array([[3, 1, 3, 9, 7, 1],
       [5, 9, 7, 8, 7, 9],
       [1, 9, 9, 4, 8, 3],
       [3, 8, 9, 6, 5, 9],
       [4, 9, 1, 3, 4, 3]])

In [69]:
arr3 > 8

array([[False, False, False,  True, False, False],
       [False,  True, False, False, False,  True],
       [False,  True,  True, False, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False, False, False]])

In [70]:
arr3[arr3 >8 ]

array([9, 9, 9, 9, 9, 9, 9, 9])

In [71]:
arr3

array([[3, 1, 3, 9, 7, 1],
       [5, 9, 7, 8, 7, 9],
       [1, 9, 9, 4, 8, 3],
       [3, 8, 9, 6, 5, 9],
       [4, 9, 1, 3, 4, 3]])

In [72]:
arr3[0:3]

array([[3, 1, 3, 9, 7, 1],
       [5, 9, 7, 8, 7, 9],
       [1, 9, 9, 4, 8, 3]])

In [73]:
arr3[0, [0,1]]

array([3, 1])

In [74]:
arr3[2:4, [2,3]]

array([[9, 4],
       [9, 6]])

In [75]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [76]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [77]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [78]:
arr1+arr2

array([[4, 3, 4],
       [2, 3, 3],
       [4, 3, 2]])

In [79]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0, -1, -1],
       [ 0, -1,  0]])

In [84]:
## Index Multiplication
arr1*arr2

array([[4, 2, 4],
       [1, 2, 2],
       [4, 2, 1]])

In [85]:
## Matrix Multiplication
arr1@arr2

array([[ 9, 10,  8],
       [ 5,  6,  5],
       [ 7,  8,  7]])

In [86]:
arr1

array([[2, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [87]:
arr2

array([[2, 2, 2],
       [1, 2, 2],
       [2, 2, 1]])

In [88]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 0.5, 0.5],
       [1. , 0.5, 1. ]])

In [89]:
arr1/0

/tmp/ipykernel_70/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

## Numpy- Broadcasting

In [96]:
arr = np.zeros((3,4))

In [97]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
a = np.array([1,2,3,4])

In [99]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [103]:
b = np.array([[3,4,5]])

In [106]:
arr1 = arr+b.T

In [107]:
b.T

array([[3],
       [4],
       [5]])

In [108]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [109]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [115]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [116]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [117]:
np.min(arr1)

3.0

In [118]:
np.max(arr1)

5.0