## Sort, Search, and Counting Functions

In [1]:
import numpy as np

In [2]:
arr = np.array([8,4,3,1,9,67,88,45])

In [3]:
arr

array([ 8,  4,  3,  1,  9, 67, 88, 45])

In [4]:
np.sort(arr)

array([ 1,  3,  4,  8,  9, 45, 67, 88])

In [6]:
np.searchsorted(arr,5)

4

In [7]:
arr1 = np.array([0,7,6,88,0,23,45,33,0,0,0,0,5,4,8])

In [8]:
arr1

array([ 0,  7,  6, 88,  0, 23, 45, 33,  0,  0,  0,  0,  5,  4,  8])

In [9]:
np.count_nonzero(arr1)

9

In [10]:
np.where(arr1>0)

(array([ 1,  2,  3,  5,  6,  7, 12, 13, 14]),)

In [11]:
np.extract(arr1 > 5, arr1)

array([ 7,  6, 88, 23, 45, 33,  8])

### Numpy- Byte Swapping

In [12]:
np.byte(arr1)

array([ 0,  7,  6, 88,  0, 23, 45, 33,  0,  0,  0,  0,  5,  4,  8],
      dtype=int8)

In [13]:
arr1.byteswap()

array([                  0,  504403158265495552,  432345564227567616,
       6341068275337658368,                   0, 1657324662872342528,
       3242591731706757120, 2377900603251621888,                   0,
                         0,                   0,                   0,
        360287970189639680,  288230376151711744,  576460752303423488])

In [14]:
arr.byteswap()

array([ 576460752303423488,  288230376151711744,  216172782113783808,
         72057594037927936,  648518346341351424, 4827858800541171712,
       6341068275337658368, 3242591731706757120])

In [15]:
arr.byteswap(True)

array([ 576460752303423488,  288230376151711744,  216172782113783808,
         72057594037927936,  648518346341351424, 4827858800541171712,
       6341068275337658368, 3242591731706757120])

In [16]:
## Numpy- Copies & Views

In [17]:
arr

array([ 576460752303423488,  288230376151711744,  216172782113783808,
         72057594037927936,  648518346341351424, 4827858800541171712,
       6341068275337658368, 3242591731706757120])

In [18]:
arr1

array([ 0,  7,  6, 88,  0, 23, 45, 33,  0,  0,  0,  0,  5,  4,  8])

In [43]:
# Creates Deep Copy
a = np.copy(arr1)

In [44]:
# Creates Shallow Copy
b= arr1.view()

In [22]:
b

array([ 0,  7,  6, 88,  0, 23, 45, 33,  0,  0,  0,  0,  5,  4,  8])

In [23]:
b[0] = 76

In [24]:
b

array([76,  7,  6, 88,  0, 23, 45, 33,  0,  0,  0,  0,  5,  4,  8])

In [25]:
arr1

array([76,  7,  6, 88,  0, 23, 45, 33,  0,  0,  0,  0,  5,  4,  8])

In [26]:
## Numpy- Matrix Library

In [28]:
import numpy.matlib as nm

In [29]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [30]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [32]:
## Numpy- Linear Algebra

In [34]:
arr1 = np.random.randint([[2,3],[4,5]])

In [35]:
arr2 = np.random.randint([[3,2],[5,4]])

In [36]:
arr1

array([[0, 2],
       [3, 3]])

In [37]:
arr2

array([[0, 0],
       [1, 2]])

In [38]:
arr1@arr2

array([[2, 4],
       [3, 6]])

In [39]:
np.dot(arr1,arr2)

array([[2, 4],
       [3, 6]])