In [1]:
import numpy as np

In [2]:
## Numpy- Array Manipulation

In [3]:
arr = np.random.randint(1,10, (4,4))

In [4]:
arr

array([[2, 3, 5, 9],
       [4, 6, 3, 6],
       [9, 8, 7, 7],
       [8, 7, 6, 8]])

In [5]:
arr.reshape(8,2)

array([[2, 3],
       [5, 9],
       [4, 6],
       [3, 6],
       [9, 8],
       [7, 7],
       [8, 7],
       [6, 8]])

In [6]:
arr.T

array([[2, 4, 9, 8],
       [3, 6, 8, 7],
       [5, 3, 7, 6],
       [9, 6, 7, 8]])

In [7]:
arr.flatten()

array([2, 3, 5, 9, 4, 6, 3, 6, 9, 8, 7, 7, 8, 7, 6, 8])

In [8]:
arr

array([[2, 3, 5, 9],
       [4, 6, 3, 6],
       [9, 8, 7, 7],
       [8, 7, 6, 8]])

In [9]:
np.expand_dims(arr, axis=1)

array([[[2, 3, 5, 9]],

       [[4, 6, 3, 6]],

       [[9, 8, 7, 7]],

       [[8, 7, 6, 8]]])

In [10]:
np.expand_dims(arr, axis=0)

array([[[2, 3, 5, 9],
        [4, 6, 3, 6],
        [9, 8, 7, 7],
        [8, 7, 6, 8]]])

In [11]:
data = np.array([[1], [2], [3], [4]])

In [12]:
np.squeeze(data)

array([1, 2, 3, 4])

In [17]:
np.squeeze(arr)

array([[2, 3, 5, 9],
       [4, 6, 3, 6],
       [9, 8, 7, 7],
       [8, 7, 6, 8]])

In [18]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [19]:
np.roll(data,2)

array([[3],
       [4],
       [1],
       [2]])

In [20]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
## Numpy- Binary Operators

In [22]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [23]:
arr1

array([[7, 2, 8, 7],
       [5, 6, 8, 8],
       [6, 7, 4, 3]])

In [24]:
arr2

array([[1, 2, 9, 8],
       [5, 3, 4, 6],
       [6, 5, 7, 2]])

In [25]:
arr1+arr2

array([[ 8,  4, 17, 15],
       [10,  9, 12, 14],
       [12, 12, 11,  5]])

In [26]:
arr1-arr2

array([[ 6,  0, -1, -1],
       [ 0,  3,  4,  2],
       [ 0,  2, -3,  1]])

In [27]:
arr1*arr2

array([[ 7,  4, 72, 56],
       [25, 18, 32, 48],
       [36, 35, 28,  6]])

In [28]:
arr1/arr2

array([[7.        , 1.        , 0.88888889, 0.875     ],
       [1.        , 2.        , 2.        , 1.33333333],
       [1.        , 1.4       , 0.57142857, 1.5       ]])

In [29]:
arr1**arr2

array([[        7,         4, 134217728,   5764801],
       [     3125,       216,      4096,    262144],
       [    46656,     16807,     16384,         9]])

In [30]:
~arr1

array([[-8, -3, -9, -8],
       [-6, -7, -9, -9],
       [-7, -8, -5, -4]])

In [31]:
arr1

array([[7, 2, 8, 7],
       [5, 6, 8, 8],
       [6, 7, 4, 3]])

In [32]:
arr1 > arr2 

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [False,  True, False,  True]])

In [34]:
## Numpy- String Functions

In [35]:
arr = np.array(["rohit","sumit"])

In [36]:
arr

array(['rohit', 'sumit'], dtype='<U5')

In [38]:
np.char.upper(arr)

array(['ROHIT', 'SUMIT'], dtype='<U5')

In [39]:
np.char.capitalize(arr)

array(['Rohit', 'Sumit'], dtype='<U5')

In [40]:
np.char.title(arr)

array(['Rohit', 'Sumit'], dtype='<U5')

In [47]:
np.char.center(arr, 3)

array(['roh', 'sum'], dtype='<U3')

In [48]:
## Numpy- Mathematical Functions

In [49]:
arr1

array([[7, 2, 8, 7],
       [5, 6, 8, 8],
       [6, 7, 4, 3]])

In [50]:
np.sin(arr1)

array([[ 0.6569866 ,  0.90929743,  0.98935825,  0.6569866 ],
       [-0.95892427, -0.2794155 ,  0.98935825,  0.98935825],
       [-0.2794155 ,  0.6569866 , -0.7568025 ,  0.14112001]])

In [51]:
np.cos(arr1)

array([[ 0.75390225, -0.41614684, -0.14550003,  0.75390225],
       [ 0.28366219,  0.96017029, -0.14550003, -0.14550003],
       [ 0.96017029,  0.75390225, -0.65364362, -0.9899925 ]])

In [52]:
np.tan(arr1)

array([[ 0.87144798, -2.18503986, -6.79971146,  0.87144798],
       [-3.38051501, -0.29100619, -6.79971146, -6.79971146],
       [-0.29100619,  0.87144798,  1.15782128, -0.14254654]])

In [53]:
np.exp(arr1)

array([[1096.63315843,    7.3890561 , 2980.95798704, 1096.63315843],
       [ 148.4131591 ,  403.42879349, 2980.95798704, 2980.95798704],
       [ 403.42879349, 1096.63315843,   54.59815003,   20.08553692]])

In [54]:
np.log10(arr1)

array([[0.84509804, 0.30103   , 0.90308999, 0.84509804],
       [0.69897   , 0.77815125, 0.90308999, 0.90308999],
       [0.77815125, 0.84509804, 0.60205999, 0.47712125]])

In [55]:
np.power(arr1,3)

array([[343,   8, 512, 343],
       [125, 216, 512, 512],
       [216, 343,  64,  27]])

In [56]:
np.mean(arr1)

5.916666666666667

In [57]:
np.median(arr1)

6.5

In [59]:
np.max(arr1)

8

In [60]:
np.min(arr1)

2

In [61]:
np.std(arr1)

1.9346977943739834

In [62]:
np.var(arr1)

3.743055555555556

In [63]:
np.sqrt(arr1)

array([[2.64575131, 1.41421356, 2.82842712, 2.64575131],
       [2.23606798, 2.44948974, 2.82842712, 2.82842712],
       [2.44948974, 2.64575131, 2.        , 1.73205081]])

In [64]:
## Numpy- Arithmetic Operations.

In [65]:
arr1

array([[7, 2, 8, 7],
       [5, 6, 8, 8],
       [6, 7, 4, 3]])

In [66]:
arr2

array([[1, 2, 9, 8],
       [5, 3, 4, 6],
       [6, 5, 7, 2]])

In [67]:
arr1+arr2

array([[ 8,  4, 17, 15],
       [10,  9, 12, 14],
       [12, 12, 11,  5]])

In [68]:
np.add(arr1,arr2)

array([[ 8,  4, 17, 15],
       [10,  9, 12, 14],
       [12, 12, 11,  5]])

In [69]:
np.subtract(arr1,arr2)

array([[ 6,  0, -1, -1],
       [ 0,  3,  4,  2],
       [ 0,  2, -3,  1]])

In [70]:
np.multiply(arr1,arr2)

array([[ 7,  4, 72, 56],
       [25, 18, 32, 48],
       [36, 35, 28,  6]])

In [71]:
np.power(arr1,arr2)

array([[        7,         4, 134217728,   5764801],
       [     3125,       216,      4096,    262144],
       [    46656,     16807,     16384,         9]])

In [72]:
np.mod(arr1,arr2)

array([[0, 0, 8, 7],
       [0, 0, 0, 2],
       [0, 2, 4, 1]])

In [73]:
np.sqrt(arr1)

array([[2.64575131, 1.41421356, 2.82842712, 2.64575131],
       [2.23606798, 2.44948974, 2.82842712, 2.82842712],
       [2.44948974, 2.64575131, 2.        , 1.73205081]])

In [74]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 3.        , 2.82842712],
       [2.23606798, 1.73205081, 2.        , 2.44948974],
       [2.44948974, 2.23606798, 2.64575131, 1.41421356]])

In [75]:
## Numpy- Statistical Functions.

In [76]:
arr1

array([[7, 2, 8, 7],
       [5, 6, 8, 8],
       [6, 7, 4, 3]])

In [77]:
np.mean(arr1)

5.916666666666667

In [78]:
np.median(arr1)

6.5

In [79]:
np.std(arr1)

1.9346977943739834

In [80]:
np.var(arr1)

3.743055555555556

In [81]:
np.max(arr2)

9