In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [7]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [8]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr1.ndim

2

In [10]:
arr.ndim

1

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
mat = np.matrix(l)
mat

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [17]:
a = arr

In [18]:
arr[0] = 100

In [19]:
arr

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
b = np.copy(arr)

In [22]:
b

array([100,   2,   3,   4])

In [23]:
b[0] = 420

In [24]:
b

array([420,   2,   3,   4])

In [25]:
arr

array([100,   2,   3,   4])

In [27]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [30]:
iterable = (i*i for i in range(5))

In [31]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [32]:
np.fromstring('23 45 76',sep = ' ')

array([23., 45., 76.])

In [33]:
np.fromstring('24,56,65', sep = ',')

array([24., 56., 65.])

In [34]:
arr

array([100,   2,   3,   4])

In [35]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
arr.ndim

1

In [37]:
arr1.ndim

2

In [38]:
arr.size

4

In [39]:
arr1.size

8

In [40]:
arr.shape

(4,)

In [41]:
arr1.shape

(2, 4)

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr1.dtype

dtype('int64')